### ISSUE TITLE
Require signatures for public key records

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-record#13]
This would allow us to validate that public keys aren't just arbitrary data.

**Comment by dirkmc** [comment]
Isn't that already being done on this line?
https://github.com/libp2p/go-libp2p-record/blob/master/validation.go#L122

**Comment by Stebalien** [comment]
That's checking to see id the DHT key equals the hash of the public key. My point here was to make sure that the key isn't just arbitrary data by forcing the publisher to actually prove that the key works as a public key (e.g, by signing something with it).

Unfortunately, it turns out that this won't help. It's usually possible to encode arbitrary data in public keys anyways, even *if* they're valid public keys.
