### ISSUE TITLE
The project and freenode badges point to IPFS

### ISSUE THREAD

**Issue by anacrolix** [libp2p/go-libp2p-record#19]
The project and freenode badges point to IPFS instead of libp2p. I'm not sure of the templating or tooling for fixing this, similar projects appear to have a custom preamble in HTML.

**Comment by Stebalien** [comment]
You can just change the URL from project-IPFS-blue to project-libp2p-blue. The main project, go-libp2p, has an HTML preamble but that's mostly because it's the main project (and has a logo, etc.).
